### ISSUE TITLE
Create separate crate for things that don't require `bevy` in `unbound-shared`

### ISSUE THREAD

**Issue by Possseidon** [Possseidon/unbound#2]
## TODO

- [x] ~Think of a name (or names if I also want to rename `unbound-shared`) for the new crate(s)~
  - `unbound-lib` should be fine for now I think
- [x] Do the refactoring
- [x] Update `README.md`
